# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Code Pages Indexer Script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  download_rails_and_run:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/scripts/Gemfile
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run indexing script
      run: bundle exec ruby scripts/make_index.rb
    - name: Commit generated files
      run: |
       git config user.name 'GitHub Actions'
       git config user.email 'actions@users.noreply.github.com'
       git add -a *.html
       timestamp=$(date -u)
       git commit -m "make index: ${timestamp}" || exit 0
       git push
